Traceback (most recent call last):
  File "/home/users/sm961/CS+/DeepLabV3Plus-Pytorch/main.py", line 665, in <module>
    main()
  File "/home/users/sm961/CS+/DeepLabV3Plus-Pytorch/main.py", line 633, in main
    loss = criterion(outputs, labels)
  File "/home/users/sm961/CS+/DeepLabV3Plus-Pytorch/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/users/sm961/CS+/DeepLabV3Plus-Pytorch/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/users/sm961/CS+/DeepLabV3Plus-Pytorch/main.py", line 522, in forward
    targets_flat = targets_one_hot.view(-1)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
srun: error: linux45: task 0: Exited with exit code 1
